# size.rb
# レディース・メンズ服
clothes = Size.create(name: "レディース・メンズ服")
clothes_1 = clothes.children.create(name: "XXS以下")
clothes_2 = clothes.children.create(name: "XS(SS)")
clothes_3 = clothes.children.create(name: "S")
clothes_4 = clothes.children.create(name: "M")
clothes_5 = clothes.children.create(name: "L")
clothes_6 = clothes.children.create(name: "XL(LL)")
clothes_7 = clothes.children.create(name: "2XL(3L)")
clothes_8 = clothes.children.create(name: "3XL(4L)")
clothes_9 = clothes.children.create(name: "4XL(5L)以上")
clothes_10 = clothes.children.create(name: "FRRE SIZE")

# キッズ靴
kids_shoes = Size.create(name: "キッズ靴")
kids_shoes_1 = kids_shoes.children.create(name: "10.5cm以下")
kids_shoes_2 = kids_shoes.children.create(name: "11cm・11.5cm")
kids_shoes_3 = kids_shoes.children.create(name: "12cm・12.5cm")
kids_shoes_4 = kids_shoes.children.create(name: "13cm・13.5cm")
kids_shoes_5 = kids_shoes.children.create(name: "14cm・14.5cm")
kids_shoes_6 = kids_shoes.children.create(name: "15cm・15.5cm")
kids_shoes_7 = kids_shoes.children.create(name: "16cm・16.5cm")
kids_shoes_8 = kids_shoes.children.create(name: "17cm以上")

# レディース・メンズ靴
shoes = Size.create(name: "レディース・メンズ靴")
shoes_1 = shoes.children.create(name: "20.0cm以下")
shoes_2 = shoes.children.create(name: "20.5cm")
shoes_3 = shoes.children.create(name: "21.0cm")
shoes_4 = shoes.children.create(name: "21.5cm")
shoes_5 = shoes.children.create(name: "22.0cm")
shoes_6 = shoes.children.create(name: "22.5cm")
shoes_7 = shoes.children.create(name: "23.0cm")
shoes_8 = shoes.children.create(name: "23.5cm以下")
shoes_9 = shoes.children.create(name: "23.5cm")
shoes_10 = shoes.children.create(name: "24.0cm")
shoes_11 = shoes.children.create(name: "24.5cm")
shoes_12 = shoes.children.create(name: "25.0cm")
shoes_13 = shoes.children.create(name: "25.5cm")
shoes_14 = shoes.children.create(name: "26.0cm")
shoes_15 = shoes.children.create(name: "26.5cm")
shoes_16 = shoes.children.create(name: "27.0cm")
shoes_17 = shoes.children.create(name: "27.5cm")
shoes_18 = shoes.children.create(name: "27.5cm以上")
shoes_19 = shoes.children.create(name: "28.0cm")
shoes_20 = shoes.children.create(name: "28.5cm")
shoes_21 = shoes.children.create(name: "29.0cm")
shoes_22 = shoes.children.create(name: "29.5cm")
shoes_23 = shoes.children.create(name: "30.0cm")
shoes_24 = shoes.children.create(name: "30.5cm")
shoes_25 = shoes.children.create(name: "31.0cm以上")

# ベビー服
baby = Size.create(name: "ベビー服")
baby_1 = baby.children.create(name: "60cm")
baby_2 = baby.children.create(name: "70cm")
baby_3 = baby.children.create(name: "80cm")
baby_4 = baby.children.create(name: "90cm")
baby_5 = baby.children.create(name: "95cm")

# キッズ服
kids_clothes = Size.create(name: "キッズ服")
kids_clothes_1 = kids_clothes.children.create(name: "100cm")
kids_clothes_2 = kids_clothes.children.create(name: "110cm")
kids_clothes_3 = kids_clothes.children.create(name: "120cm")
kids_clothes_4 = kids_clothes.children.create(name: "130cm")
kids_clothes_5 = kids_clothes.children.create(name: "140cm")
kids_clothes_6 = kids_clothes.children.create(name: "150cm")
kids_clothes_7 = kids_clothes.children.create(name: "160cm")

# テレビ・映像機器
tv = Size.create(name: "テレビ・映像機器")
tv_1 = tv.children.create(name: "〜20インチ")
tv_2 = tv.children.create(name: "20〜26インチ")
tv_3 = tv.children.create(name: "26〜32インチ")
tv_4 = tv.children.create(name: "32〜37インチ")
tv_5 = tv.children.create(name: "37〜40インチ")
tv_6 = tv.children.create(name: "40〜42インチ")
tv_7 = tv.children.create(name: "42〜46インチ")
tv_8 = tv.children.create(name: "46〜52インチ")
tv_9 = tv.children.create(name: "52〜60インチ")
tv_10 = tv.children.create(name: "60インチ〜")

# スノーボード
snow_board = Size.create(name: "スノーボード")
snow_board_1 = snow_board.children.create(name: "135cm-140cm未満")
snow_board_2 = snow_board.children.create(name: "140cm-145cm未満")
snow_board_3 = snow_board.children.create(name: "145cm-150cm未満")
snow_board_4 = snow_board.children.create(name: "150cm-155cm未満")
snow_board_5 = snow_board.children.create(name: "155cm-160cm未満")
snow_board_6 = snow_board.children.create(name: "160cm-165cm未満")
snow_board_7 = snow_board.children.create(name: "165cm-170cm未満")

# スキー板
ski = Size.create(name: "スキー板")
ski_1 = ski.children.create(name: "140cm〜")
ski_2 = ski.children.create(name: "150cm〜")
ski_3 = ski.children.create(name: "160cm〜")
ski_4 = ski.children.create(name: "170cm〜")
ski_5 = ski.children.create(name: "スキーボード")
ski_6 = ski.children.create(name: "子ども用")
ski_7 = ski.children.create(name: "その他")

# タイヤ・ホイール
tires_wheels = Size.create(name: "タイヤ・ホイール")
tires_wheels_1 = tires_wheels.children.create(name: "12インチ")
tires_wheels_2 = tires_wheels.children.create(name: "13インチ")
tires_wheels_3 = tires_wheels.children.create(name: "14インチ")
tires_wheels_4 = tires_wheels.children.create(name: "15インチ")
tires_wheels_5 = tires_wheels.children.create(name: "16インチ")
tires_wheels_6 = tires_wheels.children.create(name: "17インチ")
tires_wheels_7 = tires_wheels.children.create(name: "18インチ")
tires_wheels_8 = tires_wheels.children.create(name: "19インチ")
tires_wheels_9 = tires_wheels.children.create(name: "20インチ")
tires_wheels_10 = tires_wheels.children.create(name: "21インチ")
tires_wheels_11 = tires_wheels.children.create(name: "22インチ")
tires_wheels_12 = tires_wheels.children.create(name: "23インチ")
tires_wheels_13 = tires_wheels.children.create(name: "24インチ")

# ヘルメッド・シールド
helmed_shield = Size.create(name: "ヘルメッド・シールド")
helmed_shield_1 = helmed_shield.children.create(name: "XSサイズ以下")
helmed_shield_2 = helmed_shield.children.create(name: "Sサイズ")
helmed_shield_3 = helmed_shield.children.create(name: "Mサイズ")
helmed_shield_4 = helmed_shield.children.create(name: "Lサイズ")
helmed_shield_5 = helmed_shield.children.create(name: "XLサイズ")
helmed_shield_6 = helmed_shield.children.create(name: "XLLサイズ以上")
helmed_shield_7 = helmed_shield.children.create(name: "フリーサイズ")
helmed_shield_8 = helmed_shield.children.create(name: "子ども用")
